Version 0.1
Dhii/espresso-abstract pull request #1
Opened 2017-01-30 10:02 UTC by mecha

Initial release.

## Changelog

### Added
- Interop interfaces.
- Interface tests.

2017-01-30 10:03 UTC, mecha commented
This repository is to be moved from `dhii/espresso-abstract` to `dhii/expression-abstract` at the time of release.

2017-02-01 20:33 UTC, XedinUnknown reviewed
I would suggest moving the actual evaluation method out of `_evaluate()` into another, more low-level method, for even more control of evaluation behaviour.

2017-02-01 20:34 UTC, mecha commented
@XedinUnknown Agreed.

2017-02-02 12:09 UTC, mecha commented
@XedinUnknown Kindly see the latest commit for feedback.

2017-03-10 11:54 UTC, mecha commented
@XedinUnknown What do you think of the new namespace organization?

I'm not dead set on the `Dhii\Expression\Expression` namespace. On the one hand, everything is organized neatly; on the other hand it can be confusing since both the package and the namespace have the same name. In my opinion it's justified and not that bothering.

I'm a fan of keeping everything in its own sub namespace after the package namespace. Thoughts?

2017-03-18 14:00 UTC, XedinUnknown requested changes
I think that the logic in `AbstractExpression#_setTerms()`, which validates terms, can be reduced to just `_addTerm()` throwing.

2017-03-19 10:50 UTC, XedinUnknown requested changes

2017-03-19 10:50 UTC, XedinUnknown commented on test/functional/Context/AbstractCompositeContextTest.php
> +        $expected = array(
Why not call `_setValues()` with this?

2017-03-19 10:50 UTC, XedinUnknown commented on test/functional/Expression/AbstractExpressionTest.php
>      public function testSetTerms()
This tests exactly what I said not to test. Don't test properties. Only the methods.

2017-03-19 10:50 UTC, XedinUnknown commented on test/functional/Expression/AbstractLeftAssociativeExpressionTest.php
> +                return;
`return` is identical to `return null`. Also, it is the same as not explicitly returning anything. And that is the same as just writing `_initBuffer()`, i.e. without passing the function to it.

2017-03-19 10:50 UTC, XedinUnknown commented on test/functional/Expression/AbstractLeftAssociativeExpressionTest.php
> +            ->_initBuffer(function () {
`return` is identical to `return null`, and is exactly what happens if you don't explicitly return anything. Also, not passing anything to mocked method will return `null` from that method, This means that you can re-write this as simply `_initBuffer()`.

2017-03-19 10:50 UTC, XedinUnknown commented on test/functional/Expression/AbstractGenericExpressionTest.php
> +        $this->assertEquals($terms, $subject->this()->terms);
This does exactly what I said not to do. Please don't test properties. Test the protected getter, instead.

2017-03-19 10:59 UTC, XedinUnknown requested changes
You can add the term's index to the [error message](https://github.com/Dhii/espresso-abstract/blob/release/0.1/src/Expression/AbstractExpression.php#L49) at very little cost. This can be very helpful when debugging.

2017-03-19 12:41 UTC, mecha commented
@XedinUnknown What do you think of making the functionality outlined in [Note 2](https://github.com/Dhii/espresso-abstract/wiki/Operator-Expressions) default for right associative operators?

2017-03-19 13:16 UTC, XedinUnknown approved these changes
Thumbs up for removing Generic class, as well as making the requested changes. Extra credit for changing release date.

2017-03-19 14:13 UTC, mecha commented
@XedinUnknown Made changes to the functionality of right-associative operators and updated [the docs](https://github.com/Dhii/espresso-abstract/wiki/Operator-Expressions).

2017-03-19 14:49 UTC, merged